version: '3.8'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    container_name: wordpress-db
    restart: unless-stopped
    ports:
      - 8889:3306
    volumes:
      - mariadb_data:/bitnami/mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=&qo{&&]'_5[-@hb
      - MARIADB_USER=demo_user
      - MARIADB_PASSWORD=kc{Sh]+vj37gemC
      - MARIADB_DATABASE=demo_db
  wordpress:
    image: docker.io/bitnami/wordpress:6
    container_name: wordpress-app
    restart: unless-stopped
    ports:
      - 8888:8080
    volumes:
      - wordpress_data:/bitnami/wordpress
    depends_on:
      - mariadb
    environment:
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=demo_user
      - WORDPRESS_DATABASE_PASSWORD=kc{Sh]+vj37gemC
      - WORDPRESS_DATABASE_NAME=demo_db
      - WORDPRESS_USERNAME=admin
      - WORDPRESS_PASSWORD=12345678
      - WORDPRESS_EMAIL=contact.nahidul@gmail.com
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
